---
title: "Project title"
author:
  - name: Author Name
    affiliation:
    - &aff1 Author Institution, City, Country.
    email: email@website.com
date: "2026-02-23"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
vignette: >
  %\VignetteIndexEntry{Project title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Programming environment

```{r Set random seed, include=FALSE}
seed <- 2026-02-23
```

```{r Load packages, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(ggpubr)
library(pbapply)
library(readxl)
```

```{r Load functions, include=FALSE}
lapply(list.files("R/", full.names = TRUE), source)
```

```{r Set theme, include=FALSE}
my_theme_set()
```

```{r Session information, echo=FALSE}
sessionInfo()
```

# Data Preprocessing

## Raw data

```{r Read code book, include=FALSE}
code_book <- read_csv("inst/extdata/code_book.csv", show_col_types = FALSE)
```

```{r Show code book, echo=FALSE}
show_table(code_book, "code_book", "Code book.")
```

```{r Column-type string, include=FALSE}
coltype_str <- paste0(code_book$col_type, collapse = "")
```

```{r Raw data, include=FALSE}
raw_data <- read_csv("inst/extdata/raw_data.csv", col_types = coltype_str)
```

```{r State row and column numbers of raw data, echo=FALSE}
cat("Rows: ", nrow(raw_data), "\n")
cat("Columns: ", ncol(raw_data))
```

## Select variable of interest

```{r Variable of interest, include=FALSE}
voi <- "pe"
```

```{r Rename the variable as outcome and put after identifier, include=FALSE}
proc_data <-
  raw_data |>
  rename(outcome = voi) |>
  select(id, outcome, everything())
```

# Data partition

```{r Determine partition sample size, include=FALSE}
whole_id <- proc_data$id
whole_n <- length(whole_id)
test_n <- ceiling(0.2 * whole_n)
dev_n <- whole_n - test_n
val_n <- ceiling(0.2 * dev_n)
train_n <- dev_n - val_n
```

```{r Randomly select identifiers for each partition, include=FALSE}
set.seed(seed)
test_id <- sample(whole_id, test_n)
dev_id <- setdiff(whole_id, test_id)

set.seed(seed)
val_id <- sample(dev_id, val_n)
train_id <- setdiff(dev_id, val_id)
```

```{r Create set data, include=FALSE}
set_data <-
  data.frame(id = train_id, set = "training") |>
  rbind(data.frame(id = val_id, set = "validation")) |>
  rbind(data.frame(id = test_id, set = "testing")) |>
  mutate(set = factor(set, c("training", "validation", "testing")))
```

```{r Join set data to outcome data, include=FALSE}
outcome_set_data <-
  proc_data |>
  select(id, outcome) |>
  left_join(set_data, by = "id")
```

```{r Summarize outcome class per set, include=FALSE}
if(class(outcome_set_data$outcome) == "numeric"){
  outcome_set_summary <-
    outcome_set_data |>
    group_by(set) |>
    summarize(n = n(), .groups = "drop")
  
  outcome_set_plot <-
    outcome_set_summary |>
    ggplot(aes(set, n)) +
    geom_col()
}else{
  outcome_set_summary <-
    outcome_set_data |>
    group_by(set, outcome) |>
    summarize(n = n(), .groups = "drop")
  
  outcome_set_plot <-
    outcome_set_summary |>
    ggplot(aes(set, n, fill = outcome)) +
    geom_col()
}
```

```{r Show summary per set, echo=FALSE, fig.height=90/25.4, fig.width=190/25.4}
outcome_set_plot
```

```{r Caption outcome class summary per set, echo=FALSE}
show_figure_legend("outcome_set_plot", "Data partition.")
```

```{r Split samples using the identifiers for each partition, include=FALSE}
dev_data <- slice(proc_data, match(dev_id, id))
train_data <- slice(proc_data, match(train_id, id))
val_data <- slice(proc_data, match(val_id, id))
test_data <- slice(proc_data, match(test_id, id))
```

# Data vizualization

```{r Select numerical variables, include=FALSE}
num_data <- select_if(train_data, is.numeric)
```

```{r Select categorical variables, include=FALSE}
cat_data <- select_if(train_data, is.factor)
```

## One-variable visualization

### QQ plot

```{r State number of QQ plots, echo=FALSE}
cat("Number of QQ plots (= # of numeric variables): ", ncol(num_data))
```

```{r Create custom function for QQ plot}
qq_plotter <- function(variable, data){
  data |>
    `colnames<-`(str_replace_all(colnames(data), variable, "variable")) |>
    ggplot(aes(sample = variable)) +
  	geom_qq() +
  	geom_qq_line() +
    xlab("Normal +/- SD") +
    ylab(variable) +
    theme(axis.title = element_text(size = 10))
}
```

```{r Create QQ plots, include=FALSE}
if(ncol(num_data) > 1){
  qq_plots <- pblapply(colnames(num_data), qq_plotter, num_data)
  
  qq_ncol <- 4
  qq_nrow <- ceiling(length(qq_plots) / qq_ncol)
  qq_plots <- ggarrange(plotlist = qq_plots, ncol = qq_ncol, nrow = qq_nrow)
}
```

```{r Show QQ plots, echo=FALSE, fig.height=270/25.4, fig.width=190/25.4}
if(ncol(num_data) > 1){
  qq_plots
}
```

```{r Caption QQ plots, echo=FALSE}
if(ncol(num_data) > 1){
  show_figure_legend("qq_plots", "QQ plots.")
}
```

### Bar chart

```{r State number of bar charts, echo=FALSE}
cat("Number of bar charts (= # of categorical variables): ", ncol(cat_data))
```

```{r Create custom function for bar chart}
bar_chart_plotter <- function(variable, data){
  data |>
    `colnames<-`(str_replace_all(colnames(data), variable, "variable")) |>
    group_by(variable) |>
    summarize(n = n()) |>
    mutate(p = n / sum(n) * 100) |>
    ggplot(aes(variable, p)) +
  	geom_col() +
  	xlab(variable) +
    ylab("Proportion (%)") +
    theme(axis.title = element_text(size = 10))
}
```

```{r Create bar charts, include=FALSE}
if(ncol(cat_data) > 1){
  bar_charts <- pblapply(colnames(cat_data), bar_chart_plotter, cat_data)
  
  bc_ncol <- 4
  bc_nrow <- ceiling(length(bar_charts) / bc_ncol)
  bar_charts <- ggarrange(plotlist = bar_charts, ncol = bc_ncol, nrow = bc_nrow)
}
```

```{r Show bar charts, echo=FALSE, fig.height=54/25.4, fig.width=190/25.4}
if(ncol(cat_data) > 1){
  bar_charts
}
```

```{r Caption bar charts, echo=FALSE}
if(ncol(cat_data) > 1){
  show_figure_legend("bar_charts", "Bar charts.")
}
```

## Two-to-three-variable visualization

### Scatter plot

```{r Select num vars for these hands-on, include=FALSE}
sel_num_var <- c("age", "bmi", "uta_ri", "uta_pi", "uta_psv", "sflt1", "plgf")
```

```{r Show selected num vars for these hands-on, echo=FALSE}
cat("Only these numeric variables are visualized:\n")
sel_num_var
```

```{r State number of scatter plots, echo=FALSE}
if(ncol(num_data) >= 2){
  combn_num_var <- combn(sel_num_var, 2, simplify = FALSE)
  combn_n <- length(combn_num_var)
}else{
  comb_n <- 0
}

cat("Number of scatter plots (= # of possible pairs of num. var.): ", combn_n)
```

```{r Create custom function for scatter plot}
scatter_plotter <- function(pair, data, third = NULL){
  if(is.null(third)){
    sc_plot <-
      data |>
      select_at(pair) |>
      `colnames<-`(c("V1", "V2")) |>
      ggplot(aes(V1, V2))
  }else{
    sc_plot <-
      data |>
      select_at(c(pair, third)) |>
      `colnames<-`(c("V1", "V2", "V3")) |>
      ggplot(aes(V1, V2, color = V3))
  }
  
  sc_plot <-
    sc_plot +
    geom_point(show.legend = FALSE)  +
  	xlab(pair[1]) +
    ylab(pair[2]) +
    theme(axis.title = element_text(size = 10))
  
  if(!is.null(third)){
    sc_plot <-
      sc_plot +
      scale_color_discrete(third)
  }
  
  return(sc_plot)
}
```

```{r Create scatter plots, include=FALSE}
if(ncol(num_data) >= 2){
  sc_plots <- pblapply(combn_num_var, scatter_plotter, num_data)
  
  sc_ncol <- 4
  sc_nrow <- ceiling(length(sc_plots) / sc_ncol)
  sc_plots <- ggarrange(plotlist = sc_plots, ncol = sc_ncol, nrow = sc_nrow)
}
```

```{r Show scatter plots, echo=FALSE, fig.height=270/25.4, fig.width=190/25.4}
if(ncol(num_data) >= 2){
  sc_plots
}
```

```{r Caption scatter plots, echo=FALSE}
if(ncol(num_data) >= 2){
  show_figure_legend("sc_plots", "Scatter plots.")
}
```

```{r Create scp with color, include=FALSE}
if(ncol(num_data) >= 2 & ncol(cat_data) >= 1){
  v3 <- colnames(cat_data)[1]
  v3_data <- select(cat_data, v3)
  num_v3_data <- cbind(v3_data, num_data)
  scc_plots <- pblapply(combn_num_var, scatter_plotter, num_v3_data, v3)
  
  scc_ncol <- 4
  scc_nrow <- ceiling(length(scc_plots) / scc_ncol)
  scc_plots <- ggarrange(plotlist = scc_plots, ncol = scc_ncol, nrow = scc_nrow)
}
```

```{r Show scp with color, echo=FALSE, fig.height=270/25.4, fig.width=190/25.4}
if(ncol(num_data) >= 2 & ncol(cat_data) >= 1){
  scc_plots
}
```

```{r Caption scp with color, echo=FALSE}
if(ncol(num_data) >= 2 & ncol(cat_data) >= 1){
  show_figure_legend("sc_plots", "Scatter plots.")
}
```

### Box and violin plots

```{r Select cat vars for these hands-on, include=FALSE}
sel_cat_var <- c("outcome", "iugr")
```

```{r Show selected cat vars for these hands-on, echo=FALSE}
cat("Only these categorical variables are visualized:\n")
sel_cat_var
```

```{r State number of box plots, echo=FALSE}
if(ncol(num_data) >= 1 & ncol(cat_data) >= 1){
  combn_num_cat_var <-
    expand.grid(V1 = sel_cat_var, V2 = sel_num_var) |>
    t() |>
    as.data.frame() |>
    as.list() |>
    `names<-`(NULL)
  
  combn_nc <- length(combn_num_cat_var)
}else{
  combn_nc <- 0
}

cat("Number of box plots (= # of possible pairs of num-cat. var.): ", combn_nc)
```

```{r Create custom function for box plot}
box_plotter <- function(pair, data){
  bx_plot <-
    data |>
    select_at(pair) |>
    `colnames<-`(c("V1", "V2")) |>
    ggplot(aes(V1, V2)) +
    geom_boxplot(outliers = FALSE)
  
  set.seed(seed)
  bx_plot <-
    bx_plot +
    geom_jitter(width = 0.2)
  
  bx_plot <-
    bx_plot +
  	xlab(pair[1]) +
    ylab(pair[2]) +
    theme(axis.title = element_text(size = 10))
  
  return(bx_plot)
}
```

```{r Create box plots, include=FALSE}
if(ncol(num_data) >= 1 & ncol(cat_data) >= 1){
  bx_plots <- pblapply(combn_num_cat_var, box_plotter, train_data)
  
  bx_ncol <- 4
  bx_nrow <- ceiling(length(bx_plots) / bx_ncol)
  bx_plots <- ggarrange(plotlist = bx_plots, ncol = bx_ncol, nrow = bx_nrow)
}
```

```{r Show box plots, echo=FALSE, fig.height=216/25.4, fig.width=190/25.4}
if(ncol(num_data) >= 1 & ncol(cat_data) >= 1){
  bx_plots
}
```

```{r Caption box plots, echo=FALSE}
if(ncol(num_data) >= 1 & ncol(cat_data) >= 1){
  show_figure_legend("bx_plots", "Box plots.")
}
```

```{r Create custom function for violin plot}
violin_plotter <- function(pair, data){
  vl_plot <-
    data |>
    select_at(pair) |>
    `colnames<-`(c("V1", "V2")) |>
    ggplot(aes(V1, V2)) +
    geom_violin()
  
  set.seed(seed)
  vl_plot <-
    vl_plot +
    geom_jitter(width = 0.2)
  
  vl_plot <-
    vl_plot +
  	xlab(pair[1]) +
    ylab(pair[2]) +
    theme(axis.title = element_text(size = 10))
  
  return(vl_plot)
}
```

```{r Create violin plots, include=FALSE}
if(ncol(num_data) >= 1 & ncol(cat_data) >= 1){
  vl_plots <- pblapply(combn_num_cat_var, violin_plotter, train_data)
  
  vl_ncol <- 4
  vl_nrow <- ceiling(length(vl_plots) / vl_ncol)
  vl_plots <- ggarrange(plotlist = vl_plots, ncol = vl_ncol, nrow = vl_nrow)
}
```

```{r Show violin plots, echo=FALSE, fig.height=216/25.4, fig.width=190/25.4}
if(ncol(num_data) >= 1 & ncol(cat_data) >= 1){
  vl_plots
}
```

```{r Caption violin plots, echo=FALSE}
if(ncol(num_data) >= 1 & ncol(cat_data) >= 1){
  show_figure_legend("vl_plots", "Violin plots.")
}
```

### Stacked bar chart

```{r State number of stacked bar charts, echo=FALSE}
if(ncol(cat_data) >= 2){
  combn_cat_var <- combn(sel_cat_var, 2, simplify = FALSE)
  combn_c <- length(combn_cat_var)
}else{
  combn_c <- 0
}

cat("Number of stacked bar charts (= # of poss. pairs of cat. var.): ", combn_c)
```

```{r Create custom function for stacked bar chart}
sb_chart_plotter <- function(pair, data, mode = "proportion"){
  
  data <-
    data |>
    select_at(pair) |>
    `colnames<-`(c("V1", "V2")) |>
    group_by(V1, V2) |>
    summarize(n = n(), .groups = "drop")
  
  if(mode == "count"){
    data <-
      data |>
      mutate(y = n)
    
    ylab_txt <- "Count"
  }else{
    data <-
      data |>
      group_by(V1) |>
      mutate(y = n / sum(n) * 100)
    
    ylab_txt <- "Proportion (%)"
  }
  
  data |>
    ggplot(aes(x = V1, y = y, fill = V2)) +
    geom_col() +
    xlab(pair[1]) +
    ylab(ylab_txt) +
    scale_fill_discrete(name = pair[2]) +
    theme(
      axis.title = element_text(size = 10)
      , legend.title = element_text(size = 10)
    )
}
```

```{r Create s-bar charts, include=FALSE}
if(ncol(cat_data) >= 2){
  sb_charts <- pblapply(combn_cat_var, sb_chart_plotter, cat_data)
  
  sb_ncol <- 3
  sb_nrow <- ceiling(length(sb_charts) / sb_ncol)
  sb_charts <- ggarrange(plotlist = sb_charts, ncol = sb_ncol, nrow = sb_nrow)
}
```

```{r Show s-bar charts, echo=FALSE, fig.height=54/25.4, fig.width=190/25.4}
if(ncol(cat_data) >= 2){
  sb_charts
}
```

```{r Caption s-bar charts, echo=FALSE}
if(ncol(cat_data) >= 2){
  show_figure_legend("sb_charts", "Stacked bar charts.")
}
```

```{r Create sc-bar charts, include=FALSE}
if(ncol(cat_data) >= 2){
  cb_charts <- pblapply(combn_cat_var, sb_chart_plotter, cat_data, "count")
  
  cb_ncol <- 3
  cb_nrow <- ceiling(length(cb_charts) / cb_ncol)
  cb_charts <- ggarrange(plotlist = cb_charts, ncol = cb_ncol, nrow = cb_nrow)
}
```

```{r Show sc-bar charts, echo=FALSE, fig.height=54/25.4, fig.width=190/25.4}
if(ncol(cat_data) >= 2){
  cb_charts
}
```

```{r Caption c-bar charts, echo=FALSE}
if(ncol(cat_data) >= 2){
  show_figure_legend("cb_charts", "Stacked bar charts by count.")
}
```

## More-than-three-variable visualization

```{r Create custom function to numerize categorical variables, include=FALSE}
numerize_cat_var <- function(x){
 as.numeric(x) - 1 
}
```

```{r Prepare cluster data, include=FALSE}
cluster_data <- train_data

if(ncol(cat_data) > 0){
  cluster_data <-
    cluster_data |>
    mutate_if(is.factor, numerize_cat_var) # Numerize categorical variables
}

cluster_data <-
  cluster_data |>
  column_to_rownames(var = "id") |>
  na.omit() # Remove rows with NA in any columns
```

## Sample clustering

```{r Prepare PC1 and PC2 for sample clustering, include=FALSE}
pca_fit <-
  cluster_data |>
  prcomp(scale. = TRUE) # Data standardization

pc12_data <-
  pca_fit$x |>
  as.data.frame() |>
  select(PC1, PC2)
```

```{r Use complete linkage for hierarchical clustering, include=FALSE}
hclust_fit <-
  pc12_data |>
  dist() |>
  hclust()
```

```{r Identify cluster labels, include=FALSE}
# Modify k accordingly
h_cluster <- cutree(hclust_fit, k = 3)
```

```{r Create custom function for PC-kmean plot}
pc_hclust_pca_plotter <- function(pc_data, h_cluster, pca_fit){
  
  var_exp <-
    summary(pca_fit)$importance["Proportion of Variance", 1:2] * 100
  
  pc_data |>
    mutate(cluster = factor(h_cluster)) |>
    ggplot(aes(x = PC1, y = PC2, color = cluster)) +
    geom_point(size = 3) +
    labs(
      x = paste0("PC1 (", round(var_exp[1], 1), "%)")
      , y = paste0("PC2 (", round(var_exp[2], 1), "%)")
      , color = "Hierarchical cluster"
    )
}
```

```{r Create PC-HC plot, include=FALSE}
pc_hclust_pca_plot <- pc_hclust_pca_plotter(pc12_data, h_cluster, pca_fit)
```

```{r Show PC-HC plot, echo=FALSE, fig.height=108/25.4, fig.width=190/25.4}
pc_hclust_pca_plot
```

```{r Caption PC-kmean plot, echo=FALSE}
show_figure_legend("pc_hclust_pca_plot", "PC-HC plot.")
```

```{r Create custom function for PC-hclust plot}
pc_hclust_plotter <- function(hclust_fit, h_cluster){
  h_cluster <- factor(h_cluster)
  cols <- as.integer(h_cluster)

  plot(hclust_fit, cex = 0.6)

  labels <- hclust_fit$labels
  order <- hclust_fit$order
  usr <- par("usr")

  y1 <- usr[3] - 0.02 * diff(usr[3:4])
  y2 <- usr[3] - 0.06 * diff(usr[3:4])

  text(
    x = seq_along(order)
    , y = y2
    , labels = h_cluster[order]
    , srt = 90
    , adj = 1
    , xpd = NA
    , cex = 0.6
    , col = cols[order]
  )
}
```

```{r Show PC-hclust plot, echo=FALSE, fig.height=190/25.4, fig.width=190/25.4}
pc_hclust_plotter(hclust_fit, h_cluster)
```

```{r Caption PC-hclust plot, echo=FALSE}
show_figure_legend("pc_hclust_plotter(hclust_fit)", "PC-hclust plot.")
```


